/*
 * This source file was generated by the Gradle 'init' task
 */
package encryption;

import java.util.List;
import java.util.ArrayList;

import encryption.Model.Message;
import encryption.Util.DataManager;

public class App {
    public static void main(String[] args) {
        List<String> messages = new ArrayList<>();
        try {
            messages = DataManager.getDataFromApi(
                "https://zenquotes.io/api/quotes", "q", String.class
            );
        } catch (Exception e) {
            System.out.println(e.getMessage() + "\n");
            return;
        }
        
        for (String message : messages) {
            Message msg = new Message(message);
            msg.encryptMessage();
            System.out.println(msg);

            String decryptMessage = msg.decryptMessage();
            System.out.println(decryptMessage);
            System.out.println("Are they equal? " + msg.checkDecryptedMessage(decryptMessage));    
        }
    }
}
