/*
 * This source file was generated by the Gradle 'init' task
 */
package encryption;

import encryption.Util.SimpleLinkedList;

public class App {
    public static void main(String[] args) {
        SimpleLinkedList<String> list = new SimpleLinkedList<>();

        System.out.println(list);
        list.addFirst("b");
        list.addLast("c");
        list.addLast("d");
        list.addLast("e");
        list.addLast("f");
        list.addLast("g");
        list.addFirst("a");
        System.out.println(list);
        

        // list.addFirst(Integer.valueOf(1));
        // list.addFirst(Integer.valueOf(2))x;
        // list.addFirst(Integer.valueOf(3));
        // list.addLast(Integer.valueOf(0));
        // list.addLast(Integer.valueOf(-1));

        list.swapNodes();
        System.out.println(list);

        list.addFirst("inicio");
        list.addLast("fin");
        System.out.println(list);

    }
}
